environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 5

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - set CI=true

test_script:
  - node --version
  - npm --version
  - npm run lint
  - "node lib\\cli.js || echo Exit code: %errorlevel%"

build: off
shallow_clone: true
clone_depth: 1
version: '{build}'
matrix:
  fast_finish: true
